services:
  postgresql:
    image: postgres:15.10
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: watchdog

# docker-compose up -d --build
# docker exec -it postgresql bash
# psql -U root -d watchdog
# pg_dump -U root -d watchdog --schema-only > watchdog.sql
# docker cp postgresql:/watchdog.sql .
